const state = {
  langs: {
    "af": "Afrikaans",
    "am": "Amharic",
    "ar": "Arabic",
    "hy": "Armenian",
    "az": "Azerbaijani",
    "eu": "Basque",
    "be": "Belarusian",
    "bn": "Bengali",
    "bg": "Bulgarian",
    "ca": "Catalan",
    "zh-cn": "Chinese Simplified",
    "zh-tw": "Chinese Traditional",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "nl": "Dutch",
    "en": "English",
    "et": "Estonian",
    "fi": "Finnish",
    "fr": "French",
    "gl": "Galician",
    "ka": "Georgian",
    "de": "German",
    "el": "Greek",
    "iw": "Hebrew",
    "hi": "Hindi",
    "hu": "Hungarian",
    "is": "Icelandic",
    "id": "Indonesian",
    "it": "Italian",
    "ja": "Japanese",
    "kn": "Kannada",
    "km": "Khmer",
    "ko": "Korean",
    "ky": "Kyrgyz",
    "lo": "Lao",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "mk": "Macedonian",
    "ms": "Malay",
    "ml": "Malayalam",
    "mr": "Marathi",
    "mn": "Mongolian",
    "ne": "Nepali",
    "no": "Norwegian",
    "fa": "Persian",
    "pl": "Polish",
    "pt": "Portuguese",
    "ro": "Romanian",
    "ru": "Russian",
    "sr": "Serbian",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "es": "Spanish",
    "sw": "Swahili",
    "sv": "Swedish",
    "ta": "Tamil",
    "te": "Telugu",
    "th": "Thai",
    "tr": "Turkish",
    "uk": "Ukrainian",
    "vi": "Vietnamese",
    "zu": "Zulu"
  },
  gpc_langs: {
    "af": "af",
    "am": "am",
    "ar": "ar",
    "hy": "hy-AM",
    "az": "az-AZ",
    "eu": "eu-ES",
    "be": "be",
    "bn": "bn-BD",
    "bg": "bg",
    "ca": "ca",
    "zh-cn": "zh-CN",
    "zh-tw": "zh-TW",
    "hr": "hr",
    "cs": "cs-CZ",
    "da": "da-DK",
    "nl": "nl-NL",
    "en": "en-US",
    "et": "et",
    "fi": "fi-FI",
    "fr": "fr-FR",
    "gl": "gl-ES",
    "ka": "ka-GE",
    "de": "de-DE",
    "el": "el-GR",
    "iw": "iw-IL",
    "hi": "hi-IN",
    "hu": "hu-HU",
    "is": "is-IS",
    "id": "id",
    "it": "it-IT",
    "ja": "ja-JP",
    "kn": "kn-IN",
    "km": "km-KH",
    "ko": "ko-KR",
    "ky": "ky-KG",
    "lo": "lo-LA",
    "lv": "lv",
    "lt": "lt",
    "mk": "mk-MK",
    "ms": "ms",
    "ml": "ml-IN",
    "mr": "mr-IN",
    "mn": "mn-MN",
    "ne": "ne-NP",
    "no": "no-NO",
    "fa": "fa",
    "pl": "pl-PL",
    "pt": "pt-PT",
    "ro": "ro",
    "ru": "ru-RU",
    "sr": "sr",
    "si": "si-LK",
    "sk": "sk",
    "sl": "sl",
    "es": "es-ES",
    "sw": "sw",
    "sv": "sv-SE",
    "ta": "ta-IN",
    "te": "te-IN",
    "th": "th",
    "tr": "tr-TR",
    "uk": "uk",
    "vi": "vi",
    "zu": "zu",
  }
}

const mutations = {}

const getters = {}

const actions = {}

export default {
  state,
  mutations,
  getters,
  actions
}
